In [1]:
import pandas as pd

In [2]:
import numpy as np

In [15]:
data=np.random.randint(0,100,25).reshape(5,5)

In [16]:
data

array([[61, 78,  4, 77, 20],
       [28, 89, 43, 43, 96],
       [91, 48, 15,  1, 22],
       [46, 35, 10, 36, 52],
       [78, 84, 99, 29, 20]])

In [17]:
row='a b c d e'.split()

In [18]:
col='t1 t2 t3 t4 t5'.split()

In [19]:
row

['a', 'b', 'c', 'd', 'e']

In [20]:
col

['t1', 't2', 't3', 't4', 't5']

In [21]:
df=pd.DataFrame(data=data,index=row,columns=col)

In [22]:
df

t1  t2  t3  t4  t5
a  61  78   4  77  20
b  28  89  43  43  96
c  91  48  15   1  22
d  46  35  10  36  52
e  78  84  99  29  20

In [28]:
df.loc[['a']]

t1  t2  t3  t4  t5
a  61  78   4  77  20

In [29]:
df[['t1','t2']].loc[['a','b','c']]

t1  t2
a  61  78
b  28  89
c  91  48

In [30]:
df.loc[['a','b','c']][['t1','t2']]

t1  t2
a  61  78
b  28  89
c  91  48

In [31]:
data

array([[61, 78,  4, 77, 20],
       [28, 89, 43, 43, 96],
       [91, 48, 15,  1, 22],
       [46, 35, 10, 36, 52],
       [78, 84, 99, 29, 20]])

In [32]:
data[1:4,:3]

array([[28, 89, 43],
       [91, 48, 15],
       [46, 35, 10]])

In [33]:
df

t1  t2  t3  t4  t5
a  61  78   4  77  20
b  28  89  43  43  96
c  91  48  15   1  22
d  46  35  10  36  52
e  78  84  99  29  20

In [35]:
df.iloc[1:4,1:3]

t2  t3
b  89  43
c  48  15
d  35  10

In [36]:
d={'company':'FB FB MSFT MSFT GOOG GOOG'.split(),
    'sales':[50,20,20,30,40,10],
     'profit':[80,34,23,12,45,32]}

In [37]:
pd.Series(d)

company    [FB, FB, MSFT, MSFT, GOOG, GOOG]
sales              [50, 20, 20, 30, 40, 10]
profit             [80, 34, 23, 12, 45, 32]
dtype: object

In [40]:
df1=pd.DataFrame(d)

In [41]:
df1

company  sales  profit
0      FB     50      80
1      FB     20      34
2    MSFT     20      23
3    MSFT     30      12
4    GOOG     40      45
5    GOOG     10      32

In [45]:
df1.groupby('company').sum()

sales  profit
company               
FB          70     114
GOOG        50      77
MSFT        50      35

In [46]:
df

t1  t2  t3  t4  t5
a  61  78   4  77  20
b  28  89  43  43  96
c  91  48  15   1  22
d  46  35  10  36  52
e  78  84  99  29  20

In [47]:
data

array([[61, 78,  4, 77, 20],
       [28, 89, 43, 43, 96],
       [91, 48, 15,  1, 22],
       [46, 35, 10, 36, 52],
       [78, 84, 99, 29, 20]])

In [48]:
data[data>30]

array([61, 78, 77, 89, 43, 43, 96, 91, 48, 46, 35, 36, 52, 78, 84, 99])

In [49]:
data>30

array([[ True,  True, False,  True, False],
       [False,  True,  True,  True,  True],
       [ True,  True, False, False, False],
       [ True,  True, False,  True,  True],
       [ True,  True,  True, False, False]])

In [50]:
df

t1  t2  t3  t4  t5
a  61  78   4  77  20
b  28  89  43  43  96
c  91  48  15   1  22
d  46  35  10  36  52
e  78  84  99  29  20

In [62]:
df[df['t1']<50]

t1  t2  t3  t4  t5
b  28  89  43  43  96
d  46  35  10  36  52

In [64]:
df1

company  sales  profit
0      FB     50      80
1      FB     20      34
2    MSFT     20      23
3    MSFT     30      12
4    GOOG     40      45
5    GOOG     10      32

In [66]:
df1[df1['sales']<30][['company','profit']]

company  profit
1      FB      34
2    MSFT      23
5    GOOG      32

In [71]:
df1[df1['company']=='FB']

company  sales  profit
0      FB     50      80
1      FB     20      34

In [78]:
df1[(df1['company']=='FB') & (df1['sales']>20)]

company  sales  profit
0      FB     50      80