In [ ]:
###NumPy Continue###

In [4]:
import numpy as np

In [5]:
narr=np.array([36,27,37,39,26,16,19])

In [6]:
narr

array([36, 27, 37, 39, 26, 16, 19])

In [7]:
narr.argmax() #######gives max number index

3

In [8]:
narr.argmin()#####gives min number index

5

In [9]:
narr.sum()

200

In [10]:
narr.mean()

28.571428571428573

In [11]:
narr=np.random.randint(1,100,10).reshape(5,2)

In [12]:
narr

array([[96, 86],
       [78, 70],
       [ 9, 53],
       [32, 98],
       [ 7, 97]])

In [13]:
narr=np.random.rand(4,5)

In [14]:
narr  ###########creating data frame#######this is data

array([[0.50766421, 0.87991132, 0.01277844, 0.37421818, 0.56034766],
       [0.47284948, 0.48740959, 0.24897109, 0.47041659, 0.42891745],
       [0.12783375, 0.0408218 , 0.9433268 , 0.25471785, 0.88605211],
       [0.41397434, 0.5422786 , 0.99762748, 0.02832438, 0.18283877]])

In [15]:
row_list='w x y z'.split()
col_list='a b c d e'.split()

In [16]:
row_list

['w', 'x', 'y', 'z']

In [17]:
col_list


['a', 'b', 'c', 'd', 'e']

In [18]:
###Stitching all togethet to form data frame

In [19]:
import pandas as pd ##########DataFrame is a class

In [20]:
df=pd.DataFrame(data=narr,index=row_list,columns=col_list) #########df is a name of dataframe,first argument is data,second is row, third is column

In [21]:
df

a         b         c         d         e
w  0.507664  0.879911  0.012778  0.374218  0.560348
x  0.472849  0.487410  0.248971  0.470417  0.428917
y  0.127834  0.040822  0.943327  0.254718  0.886052
z  0.413974  0.542279  0.997627  0.028324  0.182839

In [22]:
df['a']########it returns series(data without column name)

w    0.507664
x    0.472849
y    0.127834
z    0.413974
Name: a, dtype: float64

In [23]:
df[['a']]############returns dataframe

a
w  0.507664
x  0.472849
y  0.127834
z  0.413974

In [24]:
df[['a','b']]

a         b
w  0.507664  0.879911
x  0.472849  0.487410
y  0.127834  0.040822
z  0.413974  0.542279

In [25]:
###in numpy bydefault row is selected but in pandas bydefault column get selected

In [26]:
##### ##########Using Series Class

In [27]:
df

a         b         c         d         e
w  0.507664  0.879911  0.012778  0.374218  0.560348
x  0.472849  0.487410  0.248971  0.470417  0.428917
y  0.127834  0.040822  0.943327  0.254718  0.886052
z  0.413974  0.542279  0.997627  0.028324  0.182839

In [31]:
df['a']

w    0.507664
x    0.472849
y    0.127834
z    0.413974
Name: a, dtype: float64

In [38]:
df.loc['w']

a    0.507664
b    0.879911
c    0.012778
d    0.374218
e    0.560348
Name: w, dtype: float64

In [28]:
l=[1,2,3]
n=np.array(l)
i=['a','b','c']

In [29]:
ser1=pd.Series(data=n,index=i)

In [30]:
ser1

a    1
b    2
c    3
dtype: int32

In [33]:
ser1=pd.Series(i,n)

In [34]:
ser1

1    a
2    b
3    c
dtype: object

In [35]:
ser1=pd.Series(data=l,index=n)

In [36]:
ser1

1    1
2    2
3    3
dtype: int64

In [37]:
###Series

In [38]:
list1_c=['india','usa','russia','china']

In [39]:
d={'a':1,'b':2,'c':3}

In [40]:
d

{'a': 1, 'b': 2, 'c': 3}

In [41]:
pd.Series(d)

a    1
b    2
c    3
dtype: int64

In [42]:
dict1_c={'india':4,'usa':3,'russia':2,'china':1}

In [43]:
ser1=pd.Series(dict1_c) ###########Series bydefault takes keys of dictionary as index and values as data

In [44]:
dict2_c={'india':5,'usa':2,'russia':1,'japan':1}

In [45]:
ser2=pd.Series(dict2_c)

In [46]:
ser1

india     4
usa       3
russia    2
china     1
dtype: int64

In [47]:
ser2

india     5
usa       2
russia    1
japan     1
dtype: int64

In [48]:
ser1+ser2

china     NaN
india     9.0
japan     NaN
russia    3.0
usa       5.0
dtype: float64

In [49]:
df

a         b         c         d         e
w  0.148206  0.465873  0.692621  0.836974  0.081353
x  0.044068  0.984291  0.478475  0.998256  0.424774
y  0.522934  0.295947  0.076091  0.271482  0.897140
z  0.680598  0.929164  0.071712  0.373804  0.614978

In [50]:
df.loc['w']#############returns series

a    0.148206
b    0.465873
c    0.692621
d    0.836974
e    0.081353
Name: w, dtype: float64

In [51]:
df.loc[['w']] ########returns dataframe rowwise

a         b         c         d         e
w  0.148206  0.465873  0.692621  0.836974  0.081353

In [52]:
df.loc[['w','x','y']]###multiple rows dataframe

a         b         c         d         e
w  0.148206  0.465873  0.692621  0.836974  0.081353
x  0.044068  0.984291  0.478475  0.998256  0.424774
y  0.522934  0.295947  0.076091  0.271482  0.897140

In [53]:
df.loc[['w','x']][['a','b']]##########by rows

a         b
w  0.148206  0.465873
x  0.044068  0.984291

In [54]:
n=df.loc[['w','x']]

In [55]:
df[['a','b']].loc[['w','x']]###########by columns

a         b
w  0.148206  0.465873
x  0.044068  0.984291

In [56]:
df.loc[['w','x'],['a','b']]##########fancy indexing

a         b
w  0.148206  0.465873
x  0.044068  0.984291

In [57]:
###Fancy indexing on arrays(numpy) is done on rows here in pandas fancy indexing can be done on rows by invoking .loc

In [58]:
###indexing in pandas using iloc

In [59]:
df.iloc[:3,1:4]   ########[rows,columns]

b         c         d
w  0.465873  0.692621  0.836974
x  0.984291  0.478475  0.998256
y  0.295947  0.076091  0.271482

In [60]:
##########Adding new row and column

In [61]:
df

a         b         c         d         e
w  0.148206  0.465873  0.692621  0.836974  0.081353
x  0.044068  0.984291  0.478475  0.998256  0.424774
y  0.522934  0.295947  0.076091  0.271482  0.897140
z  0.680598  0.929164  0.071712  0.373804  0.614978

In [62]:
df['fnew']=[1,2,3,4]  #########new column fnew

In [63]:
df

a         b         c         d         e  fnew
w  0.148206  0.465873  0.692621  0.836974  0.081353     1
x  0.044068  0.984291  0.478475  0.998256  0.424774     2
y  0.522934  0.295947  0.076091  0.271482  0.897140     3
z  0.680598  0.929164  0.071712  0.373804  0.614978     4

In [64]:
df.loc['v']=[1,2,3,4,5,6] #########new row 'v'

In [67]:
df

a         b         c         d         e  fnew
w  0.148206  0.465873  0.692621  0.836974  0.081353     1
x  0.044068  0.984291  0.478475  0.998256  0.424774     2
y  0.522934  0.295947  0.076091  0.271482  0.897140     3
z  0.680598  0.929164  0.071712  0.373804  0.614978     4
v  1.000000  2.000000  3.000000  4.000000  5.000000     6

In [68]:
df

a         b         c         d         e  fnew
w  0.148206  0.465873  0.692621  0.836974  0.081353     1
x  0.044068  0.984291  0.478475  0.998256  0.424774     2
y  0.522934  0.295947  0.076091  0.271482  0.897140     3
z  0.680598  0.929164  0.071712  0.373804  0.614978     4
v  1.000000  2.000000  3.000000  4.000000  5.000000     6

In [70]:
df.iloc[2:,:2]

a         b
y  0.522934  0.295947
z  0.680598  0.929164
v  1.000000  2.000000

In [71]:
d={'company':'FB FB MSFT MSFT GOOG GOOG'.split(),
    'sales':[50,20,20,30,40,10],
     'profit':[80,34,23,12,45,32]}

In [72]:
d

{'company': ['FB', 'FB', 'MSFT', 'MSFT', 'GOOG', 'GOOG'],
 'sales': [50, 20, 20, 30, 40, 10],
 'profit': [80, 34, 23, 12, 45, 32]}

In [73]:
import pandas as pd

In [74]:
df=pd.DataFrame(d)############keys of dict become columns

In [75]:
df

company  sales  profit
0      FB     50      80
1      FB     20      34
2    MSFT     20      23
3    MSFT     30      12
4    GOOG     40      45
5    GOOG     10      32

In [77]:
df.groupby('company').sum() ########group by is applicable whn elements under column is repeating and aggregate of other columns is to be done

sales  profit
company               
FB          70     114
GOOG        50      77
MSFT        50      35

In [78]:
df.groupby('company').mean()

sales  profit
company               
FB        35.0    57.0
GOOG      25.0    38.5
MSFT      25.0    17.5

In [79]:
import numpy as np

In [80]:
narr=np.random.randint(1,100,10)

In [81]:
narr

array([ 1, 13, 16, 49,  7, 61, 83, 30, 75, 40])

In [82]:
narr<50

array([ True,  True,  True,  True,  True, False, False,  True, False,
        True])

In [83]:
narr[narr<50] ############behave same as filter()

array([ 1, 13, 16, 49,  7, 30, 40])

In [84]:
df

company  sales  profit
0      FB     50      80
1      FB     20      34
2    MSFT     20      23
3    MSFT     30      12
4    GOOG     40      45
5    GOOG     10      32

In [85]:
df2=pd.DataFrame(data=np.random.rand(4,5),index='w x y z'.split(),columns='a b c d e'.split())

In [86]:
df2

a         b         c         d         e
w  0.041772  0.594906  0.358288  0.078494  0.196164
x  0.427323  0.144890  0.433226  0.321670  0.250799
y  0.493147  0.140998  0.206137  0.922483  0.338820
z  0.560405  0.795330  0.947445  0.879041  0.155074

In [87]:
df2<0.5

a      b      c      d     e
w   True  False   True   True  True
x   True   True   True   True  True
y   True   True   True  False  True
z  False  False  False  False  True

In [101]:
df2[['a']]

a
w  0.041772
x  0.427323
y  0.493147
z  0.560405

In [89]:
df2[df2<0.5]

a         b         c         d         e
w  0.041772       NaN  0.358288  0.078494  0.196164
x  0.427323  0.144890  0.433226  0.321670  0.250799
y  0.493147  0.140998  0.206137       NaN  0.338820
z       NaN       NaN       NaN       NaN  0.155074

In [90]:
########In Numpy and pandas operation is bydefault performed on evry element(result is like filter())

In [91]:
df2['a']

w    0.041772
x    0.427323
y    0.493147
z    0.560405
Name: a, dtype: float64

In [92]:
df2['a']<0.5

w     True
x     True
y     True
z    False
Name: a, dtype: bool

In [93]:
df2[df2['a']<0.5]   # filtering rows based on column condition

a         b         c         d         e
w  0.041772  0.594906  0.358288  0.078494  0.196164
x  0.427323  0.144890  0.433226  0.321670  0.250799
y  0.493147  0.140998  0.206137  0.922483  0.338820

In [94]:
df

company  sales  profit
0      FB     50      80
1      FB     20      34
2    MSFT     20      23
3    MSFT     30      12
4    GOOG     40      45
5    GOOG     10      32

In [96]:
df[df['profit']>20][['company','profit']]  ###filtering rows based on condition applied on column###showing only intended data company and profit

company  profit
0      FB      80
1      FB      34
2    MSFT      23
4    GOOG      45
5    GOOG      32

In [99]:
df[df['profit']>20][['company','sales','profit']] 

company  sales  profit
0      FB     50      80
1      FB     20      34
2    MSFT     20      23
4    GOOG     40      45
5    GOOG     10      32

In [102]:
df

company  sales  profit
0      FB     50      80
1      FB     20      34
2    MSFT     20      23
3    MSFT     30      12
4    GOOG     40      45
5    GOOG     10      32

In [103]:
df[df['company']=='MSFT']

company  sales  profit
2    MSFT     20      23
3    MSFT     30      12

In [105]:
df[(df['sales']>20)   &  (df['profit']>20)]        ###syntax  df[ ()  &  () ]

company  sales  profit
0      FB     50      80
4    GOOG     40      45

In [106]:
d={'col1':[1,2, np.nan],
    'col2':[3,np.nan,np.nan],
    'col3':[4,5,6]}

In [112]:
df=pd.DataFrame(d)       ##### np.nan is a null value from numpy array

In [113]:
## if nan is present in any column bydefault datatype is float

In [114]:
df

col1  col2  col3
0   1.0   3.0     4
1   2.0   NaN     5
2   NaN   NaN     6

In [115]:
df.dropna()

col1  col2  col3
0   1.0   3.0     4

In [116]:
df.dropna(thresh=2)  ## drop all rows with two nan values

col1  col2  col3
0   1.0   3.0     4
1   2.0   NaN     5

In [117]:
df.dropna(axis=1)    ## drop columns with nan;  axis=0 for row and axis=1 for column

col3
0     4
1     5
2     6

In [119]:
df.dropna(axis=1,thresh=2)   # drop columns with atleast two nan values

col1  col3
0   1.0     4
1   2.0     5
2   NaN     6

In [120]:
df

col1  col2  col3
0   1.0   3.0     4
1   2.0   NaN     5
2   NaN   NaN     6

In [121]:
## filling in nan

In [122]:
df.fillna('fillvalue')

col1       col2  col3
0          1          3     4
1          2  fillvalue     5
2  fillvalue  fillvalue     6

In [123]:
df['col1'].fillna('FV')

0     1
1     2
2    FV
Name: col1, dtype: object

In [124]:
df['col1'].mean()

1.5

In [125]:
df['col1'].fillna(df['col1'].mean(), inplace=True)  ### inplace makes changes permanant in original df

In [126]:
df

col1  col2  col3
0   1.0   3.0     4
1   2.0   NaN     5
2   1.5   NaN     6

In [127]:
df['col2'].fillna(df['col2'].mean(),inplace=True)

In [128]:
df

col1  col2  col3
0   1.0   3.0     4
1   2.0   3.0     5
2   1.5   3.0     6

In [131]:
d={'col1':[444, 555, 444, 666],
    'col2':[1,2,3,4],
     'col3':'mike john sarah jammie'.split()}

In [132]:
d

{'col1': [444, 555, 444, 666],
 'col2': [1, 2, 3, 4],
 'col3': ['mike', 'john', 'sarah', 'jammie']}

In [133]:
df=pd.DataFrame(d)

In [134]:
df

col1  col2    col3
0   444     1    mike
1   555     2    john
2   444     3   sarah
3   666     4  jammie

In [135]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
col1    4 non-null int64
col2    4 non-null int64
col3    4 non-null object
dtypes: int64(2), object(1)
memory usage: 176.0+ bytes


In [136]:
df.head()   # head() bydefault gives first five rows

col1  col2    col3
0   444     1    mike
1   555     2    john
2   444     3   sarah
3   666     4  jammie

In [137]:
df.head(2)

col1  col2  col3
0   444     1  mike
1   555     2  john

In [138]:
df['col1'].nunique()   ## gives no of unique elements in col

3

In [140]:
df['col1'].unique()  ## gives array of unique elements

array([444, 555, 666], dtype=int64)

In [142]:
df['col1'].value_counts() ### gives values

444    2
555    1
666    1
Name: col1, dtype: int64

In [143]:
def twice(num):
    return 2*num

In [144]:
twice(2)

4

In [146]:
##making new column which applies fun twice

In [147]:
df['new']=df['col2'].apply(twice)

In [148]:
df

col1  col2    col3  new
0   444     1    mike    2
1   555     2    john    4
2   444     3   sarah    6
3   666     4  jammie    8